---
- name: Install MongoDB
  hosts: all
  become: true
  tasks:
  
   - name: Add an Apt signing key, uses whichever key is at the URL
     apt_key:
      url: http://www.mongodb.org/static/pgp/server-4.2.asc
      state: present

   - name: Add specified repository into sources list using specified filename
     apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
      state: present
      filename: /etc/apt/sources.list.d/mongodb-org-4.2.list

   - name: Install MongoDB
     apt:
      update_cache: yes
      name: mongodb-org
      state: present

   - name: Enable and start MongoDM
     systemd:
      name: mongod
      state: started
      enabled: yes
